version: '3'
services:
  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_USER=myuser
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h mysql-standalone -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8089:8085
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
         - mysql-standalone
               


