version: '3'
services:
  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - 3307:3306
    
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8089:8085
    build:
      context: .
      dockerfile: Dockerfile
      command: ["./wait-for-it.sh", "mysql-standalone:3306", "--", "java",  "-jar", "docker-mk.war"]
    depends_on:
          mysql-standalone
               


